#!/bin/bash

###############################################################
# Author : Orapeleng Ditsoane
# Date : 13/01/2026
##############################################################


LOG_FILE="$1"

if [ -z "$LOG_FILE" ] || [ ! -f "$LOG_FILE" ]; then
        echo "Usage: $0 <nginx_access_log_file>"
        exit 1

fi

echo "####################################"
echo " Top 5 IP Address"
echo "####################################"
awk '{print $1}' "$LOG_FILE" \
        | sort \ #group identical entries
        | uniq -c \ #Ccount them
        | sort -nr \ #highest count first
        | head -5 #show top 5 only


echo 
echo "######################################"
echo " Top 5 Response Status Codes"
echo "######################################"
awk '{print $9}' "$LOG_FILE" \
        | sort \
        | uniq -c \
        | sort -nr \
        | head -5

echo 
echo "######################################"
echo " Top 5 Requested Paths"
echo "#####################################"
awk -F\" '{print $2}' "$LOG_FILE" \
        | awk '{print $2}' \
        | sort \
        | uniq -c \
        | sort -nr \
        | head -5

echo 
echo "##################################"
echo " Top 5 User Agents"
echo "##################################"
awk -F\" '{print $6}' "$LOG_FILE" \
        | sort \
        | uniq -c \
        | sort -nr \
        | head -5
